language: php

php:
  - 5.3
  - 5.4
  - 5.5

branches:
  only:
    - cis-phpunit

before_script:
  - composer install --dev --no-progress

script: phpunit --coverage-text --configuration tests/phpunit.xml